### ISSUE TITLE
No module named 'pysftp'

### ISSUE THREAD

**Issue by tiagochst** [Sage-Bionetworks/synapser#226]
## Operating system

Max OSX

## Description of the problem

Cannot upload data using the package. It says: No module named 'pysftp', but pysftp is installed for Python 3.6.4.

```
fileEntity <- synGet("syn18265702")
file <- File(path ="~/Downloads/merged_metadata.csv", parent = fileEntity)
file <- synStore(file)
```

### Expected behavior

File upload

### Actual behavior

`Error in value[[3L]](cond) : No module named 'pysftp'`

## Output of `sessionInfo()`

```
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.14

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] synapserutils_0.1.4 synapser_0.5.45

loaded via a namespace (and not attached):
[1] compiler_3.5.1        R6_2.3.0              codetools_0.2-16
[4] pack_0.1-1            PythonEmbedInR_0.3.25
```

**Comment by kimyen** [comment]
@tiagochst,

Thank you for reporting the issue and include detailed information! We appreciate it.
Our `synapser` wraps our Python client. However, `synapser` manages its own Python environment and this Python environment is separated from user's Python environment. 
In the Python environment that is managed by `synapser`, we do not include `pysftp` package. 

You probably running into this issue because you were downloading files that are hosted from an SFTP server and linked to Synapse. `synapser` client is not supporting this usage. 

Although, perhaps we should throw a more reasonable error in this case. I would advice to use out web client or our Python client to download these files.

**Comment by kimyen** [comment]
The folder that you are uploading the file to has storage setting set to sftp: 
<img width="1473" alt="screen shot 2019-02-13 at 1 14 13 pm" src="https://user-images.githubusercontent.com/4404426/52744391-761ebc80-2f91-11e9-9dd2-b370e2c21d40.png">

**Comment by tiagochst** [comment]
Thanks! I used the Python client and I was able to upload the data.
